language: php

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
    env: ANALYSIS='true'
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- composer install -n

script:
- echo "build travis"    
- if [[ "$ANALYSIS" != 'true' ]]; then vendor/bin/phpunit ; fi
- if [[ "$ANALYSIS" == 'true' ]]; then vendor/bin/phpcs ; fi

