language: php

matrix:
  include:
  - php: 7.2
    env: ANALYSIS='true'

  allow_failures:
  - php: nightly

before_script:
- composer install

script:
- echo "build travis" 
- composer update
- sudo apt-get install php-codesniffer
- phpcs --version





