language: php

matrix:
  include:
  - php: 7.2
    env: ANALYSIS='true'
  - php: nightly

  allow_failures:
  - php: nightly

before_script:
- composer install

script:
- echo "build travis"    
- phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
