<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf92ed66a129003ddfb3e5b53da0d34f1
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf92ed66a129003ddfb3e5b53da0d34f1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf92ed66a129003ddfb3e5b53da0d34f1::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
